### ISSUE TITLE
Weapon_PPC_PPCER_0-STOCK.json Rarity and Purchasable tags are wrong

### ISSUE THREAD

**Issue by scJazz2** [DrBuckarooBanzai/cFixes#6]
compared to values in stock 1.2 version...
Also... do not think this file should be included at all since 1.3 will probably change these values and fix the accuracy debuff.
Should re-check after 1.3 release IMHO.

**Comment by DrBuckarooBanzai** [comment]
error was mine, file got drawn from helm core dawning mod. fixed the issue.
